"""Add user and document-user relationship

Revision ID: 52d8b492c007
Revises: 
Create Date: 2025-07-29 13:24:08.324630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = '52d8b492c007'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    inspector = inspect(op.get_bind())

    # Verificar y eliminar tablas solo si existen
    if 'auditoria_descargas' in inspector.get_table_names():
        op.drop_table('auditoria_descargas')
    if 'manuales' in inspector.get_table_names():
        op.drop_table('manuales')
    if 'packs' in inspector.get_table_names():
        op.drop_table('packs')
    if 'categorias' in inspector.get_table_names():
        op.drop_table('categorias')

    # Crear nuevas tablas y relaciones solo si no existen
    if 'usuario' not in inspector.get_table_names():
        op.create_table(
            'usuario',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=80), nullable=False),
            sa.Column('password', sa.String(length=200), nullable=False),
            sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('username')
        )

    # Crear un usuario predeterminado si no existe
    op.execute("INSERT IGNORE INTO usuario (id, username, password, fecha_creacion) VALUES (1, 'default_user', 'default_password', NOW())")

    # Verificar si la columna usuario_id ya existe antes de agregarla
    if 'usuario_id' not in [col['name'] for col in inspector.get_columns('manual')]:
        with op.batch_alter_table('manual', schema=None) as batch_op:
            batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))

    # Asignar un valor predeterminado a usuario_id para filas existentes
    op.execute("UPDATE manual SET usuario_id = 1 WHERE usuario_id IS NULL")

    with op.batch_alter_table('manual', schema=None) as batch_op:
        batch_op.alter_column('usuario_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_foreign_key('fk_manual_usuario', 'usuario', ['usuario_id'], ['id'])

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categorias_nombre'))

    op.drop_table('categorias')
    op.drop_table('pack')
    op.drop_table('packs')
    op.drop_table('auditoria_descargas')
    with op.batch_alter_table('manuales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_manual_categoria_fecha'))
        batch_op.drop_index(batch_op.f('ix_manuales_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_manuales_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_manuales_titulo'))

    op.drop_table('manuales')
    with op.batch_alter_table('manual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('manual_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('pack_id')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('nombre')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False))
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    with op.batch_alter_table('manual', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('manual_ibfk_2'), 'pack', ['pack_id'], ['id'])
        batch_op.drop_column('usuario_id')

    op.create_table('manuales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('archivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('archivo_original', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('tamaño_archivo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_archivo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('fecha_actualizacion', mysql.DATETIME(), nullable=False),
    sa.Column('descargas', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pack_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name='manuales_ibfk_1'),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], name='manuales_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('manuales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manuales_titulo'), ['titulo'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuales_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_manuales_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_manual_categoria_fecha'), ['categoria_id', 'fecha_creacion'], unique=False)

    op.create_table('auditoria_descargas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('manual_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fecha_descarga', mysql.DATETIME(), nullable=False),
    sa.Column('ip_usuario', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.ForeignKeyConstraint(['manual_id'], ['manuales.id'], name=op.f('auditoria_descargas_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('packs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], name=op.f('packs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pack',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('categoria_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], name=op.f('pack_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categorias',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('descripcion', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=False),
    sa.Column('activa', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categorias_nombre'), ['nombre'], unique=True)

    # ### end Alembic commands ###
